# Generated by Django 5.2.7 on 2025-11-10 20:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='muscle_groups/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mushak guruhi',
                'verbose_name_plural': 'Mushak guruhlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField()),
                ('image', models.ImageField(upload_to='programs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('name_uz', models.CharField(blank=True, max_length=200, verbose_name="O'zbek nomi")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='exercises/thumbnails/', verbose_name='Rasm')),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='exercises/details/', verbose_name='Batafsil rasm')),
                ('video', models.FileField(blank=True, null=True, upload_to='exercises/videos/', verbose_name='Video')),
                ('difficulty', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Murakkab')], default='intermediate', max_length=20, verbose_name='Qiyinlik darajasi')),
                ('equipment', models.CharField(blank=True, max_length=200, verbose_name='Asboblar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='apps.musclegroup', verbose_name='Mushak guruhi')),
            ],
            options={
                'verbose_name': 'Mashq',
                'verbose_name_plural': 'Mashqlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('name_uz', models.CharField(blank=True, max_length=100, verbose_name="O'zbek nomi")),
                ('position_top', models.FloatField(default=0, verbose_name='Top pozitsiya (front %)')),
                ('position_left', models.FloatField(default=0, verbose_name='Left pozitsiya (front %)')),
                ('back_position_top', models.FloatField(blank=True, default=0, null=True, verbose_name='Top pozitsiya (back %)')),
                ('back_position_left', models.FloatField(blank=True, default=0, null=True, verbose_name='Left pozitsiya (back %)')),
                ('label_top', models.FloatField(blank=True, default=0, null=True, verbose_name='Label top %')),
                ('label_left', models.FloatField(blank=True, default=0, null=True, verbose_name='Label left %')),
                ('back_label_top', models.FloatField(blank=True, default=0, null=True, verbose_name='Back label top %')),
                ('back_label_left', models.FloatField(blank=True, default=0, null=True, verbose_name='Back label left %')),
                ('side', models.CharField(choices=[('front', 'Old tomon'), ('back', 'Orqa tomon'), ('both', 'Ikkala tomon')], default='front', max_length=10, verbose_name='Tomon')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_parts', to='apps.musclegroup', verbose_name='Mushak guruhi')),
            ],
            options={
                'verbose_name': 'Tana qismi',
                'verbose_name_plural': 'Tana qismlari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'To langan'), ('failed', 'Muvaffaqiyatsiz'), ('refunded', 'Qaytarilgan')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "To'lov tarixi",
                'verbose_name_plural': "To'lovlar tarixi",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('uzcard', 'UzCard'), ('humo', 'Humo')], max_length=20, verbose_name='Karta turi')),
                ('card_token', models.CharField(max_length=100, unique=True, verbose_name='Karta token (Click)')),
                ('card_last_four', models.CharField(max_length=4, verbose_name='Oxirgi 4 raqam')),
                ('expiry_month', models.CharField(max_length=2, verbose_name='Amal qilish oyi')),
                ('expiry_year', models.CharField(max_length=4, verbose_name='Amal qilish yili')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "To'lov usuli",
                'verbose_name_plural': "To'lov usullari",
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.CharField(default=0)),
                ('duration_weeks', models.CharField(help_text='Dastur davomiyligi (haftalarda)')),
                ('days_per_week', models.CharField(default=3, help_text='Haftasiga necha kun')),
                ('description', models.CharField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='editions/')),
                ('color', models.CharField(default='#FF6B35', help_text='Kartochka rangi (hex)', max_length=7)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='apps.program')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateTimeField(verbose_name='Tugash sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Avtomatik yangilash')),
                ('price', models.DecimalField(decimal_places=2, default=67000.0, max_digits=10, verbose_name='Oylik narx (UZS)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('subscription_new', 'Yangi obuna'), ('subscription_renew', 'Obuna yangilandi'), ('subscription_auto', "Avtomatik to'lov")], max_length=30, verbose_name="To'lov turi")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor (UZS)')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarildi'), ('failed', 'Muvaffaqiyatsiz'), ('refunded', 'Qaytarildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('click_trans_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Click Transaction ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Merchant Transaction ID')),
                ('is_auto_payment', models.BooleanField(default=False, verbose_name="Avtomatik to'lovmi")),
                ('auto_payment_attempt', models.IntegerField(default=0, verbose_name="Avtomatik to'lov urinishi")),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha ma'lumotlar")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='apps.subscription', verbose_name='Obuna')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=255)),
                ('is_premium', models.BooleanField(default=False)),
                ('name', models.CharField(default='User', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('fitness_goal', models.CharField(blank=True, choices=[('build_body', 'Build a great body'), ('lose_weight', 'Lose weight'), ('gain_muscle', 'Gain muscle'), ('get_shape', 'Get in shape')], max_length=20)),
                ('workout_days_per_week', models.IntegerField(blank=True, null=True)),
                ('unit_system', models.CharField(choices=[('metric', 'Metric'), ('english', 'English')], default='metric', max_length=10)),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('en', 'English'), ('ru', 'Русский')], default='uz', max_length=5)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('subscription_start_date', models.DateField(blank=True, null=True)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('subscription_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('bot_start', 'Bot Started'), ('onboarding_started', 'Onboarding Started'), ('onboarding_completed', 'Onboarding Completed'), ('subscription_page_viewed', 'Subscription Page Viewed'), ('payment_initiated', 'Payment Initiated'), ('payment_completed', 'Payment Completed'), ('program_viewed', 'Program Viewed'), ('workout_started', 'Workout Started'), ('workout_completed', 'Workout Completed'), ('exercise_viewed', 'Exercise Viewed'), ('exercise_favourited', 'Exercise Favourited')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='apps.userprofile')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi faoliyati',
                'verbose_name_plural': 'Foydalanuvchi faoliyatlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('day_number', models.CharField(help_text='Edition ichida nechanchi kun')),
                ('order', models.CharField(default=0)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='apps.edition')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('edition', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(default=0)),
                ('sets', models.CharField(default=3)),
                ('reps', models.CharField(blank=True, default=12, null=True)),
                ('duration_seconds', models.CharField(blank=True, help_text='Cardio uchun (sekundlarda)', null=True)),
                ('duration_type', models.CharField(choices=[('reps', 'Reps'), ('time', 'Time')], default='reps', max_length=10)),
                ('recommended_weight', models.FloatField(blank=True, help_text="Tavsiya etiladigan og'irlik (kg)", null=True)),
                ('rest_seconds', models.CharField(default=60, help_text='Dam olish vaqti (sekundlarda)')),
                ('notes', models.CharField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='apps.workout')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='Qadam raqami')),
                ('text', models.TextField(verbose_name='Matn')),
                ('text_uz', models.TextField(blank=True, verbose_name="O'zbek matn")),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='apps.exercise', verbose_name='Mashq')),
            ],
            options={
                'verbose_name': "Mashq ko'rsatmasi",
                'verbose_name_plural': "Mashq ko'rsatmalari",
                'ordering': ['step_number'],
                'unique_together': {('exercise', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Obyekt ID')),
                ('collection', models.CharField(blank=True, max_length=100, null=True, verbose_name="To'plam")),
                ('notes', models.TextField(blank=True, verbose_name='Eslatmalar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Sevimli',
                'verbose_name_plural': 'Sevimlilar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'content_type'], name='apps_favori_user_id_d76560_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('icon', models.CharField(default='⭐', max_length=10, verbose_name='Icon')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_collections', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Sevimlilar to'plami",
                'verbose_name_plural': "Sevimlilar to'plamlari",
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserMotivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.CharField(choices=[('healthy_lifestyle', 'I want a healthy lifestyle'), ('improve_physique', 'Improve my physique'), ('get_stronger', 'Get stronger every day'), ('good_challenge', 'I like a good challenge')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Motivation',
                'verbose_name_plural': 'User Motivations',
                'unique_together': {('user', 'motivation')},
            },
        ),
    ]
